{"uuid": "89594c14-4fd1-42b1-8821-45cca3fa349f", "children": ["533c2781-d753-4c52-bc6e-1a252a44c9d9", "7fcd8d09-8eb5-4f49-8b61-767a3966d63b"], "befores": [{"name": "log_in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.86)\nStacktrace:\n0   chromedriver                        0x0000000105f94e82 chromedriver + 6696578\n1   chromedriver                        0x0000000105f8cc9a chromedriver + 6663322\n2   chromedriver                        0x0000000105994e3e chromedriver + 405054\n3   chromedriver                        0x000000010596a1fa chromedriver + 229882\n4   chromedriver                        0x0000000105a12f9d chromedriver + 921501\n5   chromedriver                        0x0000000105a2cde4 chromedriver + 1027556\n6   chromedriver                        0x0000000105a0a613 chromedriver + 886291\n7   chromedriver                        0x00000001059d7950 chromedriver + 678224\n8   chromedriver                        0x00000001059d834e chromedriver + 680782\n9   chromedriver                        0x0000000105f62770 chromedriver + 6489968\n10  chromedriver                        0x0000000105f65219 chromedriver + 6500889\n11  chromedriver                        0x0000000105f64d3b chromedriver + 6499643\n12  chromedriver                        0x0000000105f656a5 chromedriver + 6502053\n13  chromedriver                        0x0000000105f4d524 chromedriver + 6403364\n14  chromedriver                        0x0000000105f6598f chromedriver + 6502799\n15  chromedriver                        0x0000000105f3e954 chromedriver + 6342996\n16  chromedriver                        0x0000000105f7d378 chromedriver + 6599544\n17  chromedriver                        0x0000000105f7d535 chromedriver + 6599989\n18  chromedriver                        0x0000000105f8c868 chromedriver + 6662248\n19  libsystem_pthread.dylib             0x00007ff815672202 _pthread_start + 99\n20  libsystem_pthread.dylib             0x00007ff81566dbab thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dchernukha/PycharmProjects/Diplom/Diplom_3/conftest.py\", line 25, in log_in\n    main_page.click_login_into_account_button()\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/dchernukha/PycharmProjects/Diplom/Diplom_3/pages/main_page.py\", line 9, in click_login_into_account_button\n    self.move_to_element_and_click(MainPageLocators.LOGIN_INTO_ACCOUNT_BUTTON)\n  File \"/Users/dchernukha/PycharmProjects/Diplom/Diplom_3/pages/base_page.py\", line 14, in move_to_element_and_click\n    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable(locator))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py\", line 363, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Нажимаем на кнопку Войти в аккаунт", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.86)\nStacktrace:\n0   chromedriver                        0x0000000105f94e82 chromedriver + 6696578\n1   chromedriver                        0x0000000105f8cc9a chromedriver + 6663322\n2   chromedriver                        0x0000000105994e3e chromedriver + 405054\n3   chromedriver                        0x000000010596a1fa chromedriver + 229882\n4   chromedriver                        0x0000000105a12f9d chromedriver + 921501\n5   chromedriver                        0x0000000105a2cde4 chromedriver + 1027556\n6   chromedriver                        0x0000000105a0a613 chromedriver + 886291\n7   chromedriver                        0x00000001059d7950 chromedriver + 678224\n8   chromedriver                        0x00000001059d834e chromedriver + 680782\n9   chromedriver                        0x0000000105f62770 chromedriver + 6489968\n10  chromedriver                        0x0000000105f65219 chromedriver + 6500889\n11  chromedriver                        0x0000000105f64d3b chromedriver + 6499643\n12  chromedriver                        0x0000000105f656a5 chromedriver + 6502053\n13  chromedriver                        0x0000000105f4d524 chromedriver + 6403364\n14  chromedriver                        0x0000000105f6598f chromedriver + 6502799\n15  chromedriver                        0x0000000105f3e954 chromedriver + 6342996\n16  chromedriver                        0x0000000105f7d378 chromedriver + 6599544\n17  chromedriver                        0x0000000105f7d535 chromedriver + 6599989\n18  chromedriver                        0x0000000105f8c868 chromedriver + 6662248\n19  libsystem_pthread.dylib             0x00007ff815672202 _pthread_start + 99\n20  libsystem_pthread.dylib             0x00007ff81566dbab thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/dchernukha/PycharmProjects/Diplom/Diplom_3/pages/main_page.py\", line 9, in click_login_into_account_button\n    self.move_to_element_and_click(MainPageLocators.LOGIN_INTO_ACCOUNT_BUTTON)\n  File \"/Users/dchernukha/PycharmProjects/Diplom/Diplom_3/pages/base_page.py\", line 14, in move_to_element_and_click\n    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable(locator))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py\", line 363, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732720790961, "stop": 1732720790963}], "start": 1732720790961, "stop": 1732720790974}], "start": 1732720790961, "stop": 1732720791019}